---
# tasks file for ansible-el-nodejs
- name: Ensure epel-release is installed
  yum:
    name: epel-release
    state: latest
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install nodejs
  yum:
    name: "{{ item }}"
    state: latest
  with_items: " {{ ansible_el_nodejs__packages }}"

- name: Install PM2 process manager using npm
  npm:
    name: pm2
    global: yes
  when: "{{ ansible_el_nodejs__install_pm2 }}"

- name: Install other npm packages
  npm:
    name: "{{ item.name }}"
    global: "{{ item.global }}"
  with_items:
    "{{ ansible_el_nodejs__npm_packages }}"
  when: ansible_el_nodejs__npm_packages is defined

- name: Create pm2 process user {{ ansible_el_nodejs__pm2user }}
  user:
    name: "{{ ansible_el_nodejs__pm2user }}"
    state: present
  when: ansible_el_nodejs__pm2user is defined

- name: Deploy ssh keys to user {{ ansible_el_nodejs__pm2user }}
  authorized_key:
    user: "{{ ansible_el_nodejs__pm2user }}"
    state: present
    exclusive: true
    key: "{{ item }}"
  with_file:
    "{{ ansible_el_nodejs__pm2user_public_keys_file }}"
  when: ansible_el_nodejs__pm2user_public_keys_file is defined
